package agent

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/blackpaw-studio/leo/internal/agentstore"
	"github.com/blackpaw-studio/leo/internal/config"
	claudeharness "github.com/blackpaw-studio/leo/internal/harness/claude"
)

// resolveOpeningPrompt decides how a claude agent's initial-spawn opening
// prompt reaches its launch argv. tmux 3.6a rejects any client command over
// ~16 KiB ("command too long"), and BuildTemplateArgs' literal trailing
// positional would blow well past that for a large prompt — so instead the
// prompt is written to a private per-agent brief file, keyed by a freshly
// generated random id (claudeharness.GenerateAgentBriefID/AgentBriefPathForID
// — deliberately NOT derived from the agent name, so a rename followed by a
// fresh spawn under the freed name can never collide with an old brief), and
// delivered as a small $(cat ...) command substitution word, the same
// mechanism PR #218 uses for interactive dispatch. The returned id is carried
// on a TYPED field (SpawnRequest.OpeningBriefID / agentstore.Record.
// OpeningBriefID) all the way to the supervisor, which re-derives and
// Lstat-safety-checks the path itself (see service.resolveOpeningBriefPath)
// before appending the substitution — it never rides inside ClaudeArgs, so
// nothing in that slice (hand-authored config, a persisted record, or
// anything else) can ever smuggle unquoted shell text into the launch
// command.
//
// Called only for the claude harness, and only at initial spawn (Start/
// Restart never call this — see resolveTemplateWiring, which always passes
// an empty prompt to BuildTemplateArgs and never sets OpeningBriefID on the
// rebuilt record, so a restart/resume never re-sends the opening prompt,
// matching the pre-existing invariant unchanged; Reset instead carries the
// ORIGINAL record's OpeningBriefID forward unchanged, since Reset replays
// the original spawn's ClaudeArgs verbatim too).
//
// Returns briefID == "" when prompt is empty (no brief needed at all). An
// oversized prompt (above claudeharness.ArgvPromptLimit) is rejected outright
// with a clear error: unlike interactive dispatch's injectOpening, an
// ephemeral claude agent has no tmux-paste-injection fallback once launched,
// so silently truncating or dropping the prompt would be worse than failing
// the spawn.
func resolveOpeningPrompt(cfg *config.Config, agentName, prompt string) (briefID string, err error) {
	if prompt == "" {
		return "", nil
	}
	if !claudeharness.DeliversPromptViaArgv(prompt) {
		return "", fmt.Errorf("opening prompt is %d bytes, exceeding the %d byte launch-time limit for a claude agent", len(prompt), claudeharness.ArgvPromptLimit)
	}
	id, err := claudeharness.GenerateAgentBriefID()
	if err != nil {
		return "", fmt.Errorf("generating opening-brief id: %w", err)
	}
	path, err := claudeharness.AgentBriefPathForID(cfg.HomePath, id)
	if err != nil {
		// Unreachable in practice (id was just generated by us), but never
		// silently drop the prompt if it somehow happens.
		return "", fmt.Errorf("deriving opening-brief path: %w", err)
	}
	if err := claudeharness.WritePrivateBrief(path, prompt); err != nil {
		return "", fmt.Errorf("writing opening-prompt brief: %w", err)
	}
	return id, nil
}

// removeOpeningPromptBrief deletes id's brief file, if any, after validating
// id — Delete's only call site, so a hand-edited or corrupted agentstore
// record can never make this remove an arbitrary path. Best-effort: a
// missing file is not an error, and a removal failure is logged rather than
// surfaced, matching removeSettingsSpill's contract for the sibling spill
// file.
//
// Deliberately NOT called from Stop or Rename: Reset replays the original
// agentstore record's OpeningBriefID verbatim (see resolveOpeningPrompt), so
// a stop-then-reset (or a rename, which needs no file handling at all — the
// id travels with the record regardless of name) must not lose the file a
// later Reset needs. It is removed only on Delete (the agent is gone for
// good) — SweepOpeningPromptBriefs cleans up files a Restart/Start has since
// orphaned by clearing the field without removing the file.
func removeOpeningPromptBrief(homePath, id string) {
	if id == "" {
		return
	}
	path, err := claudeharness.AgentBriefPathForID(homePath, id)
	if err != nil {
		log.Printf("removing opening-prompt brief: invalid id %q: %v", id, err)
		return
	}
	if err := claudeharness.RemoveBrief(path); err != nil {
		log.Printf("removing opening-prompt brief %q: %v", path, err)
	}
}

// SweepOpeningPromptBriefs removes agent-briefs files that are unsafe or that
// no agentstore record's OpeningBriefID references any more — e.g. a
// Restart/Start cleared the field on the record that used to own the file
// (see resolveOpeningPrompt), or the record itself is gone entirely.
// Best-effort, for daemon startup; mirrors SweepSettingsSpills for the
// sibling settings-spill mechanism.
//
// Every *.txt entry in the dir is inspected individually:
//   - a basename that isn't a valid brief id (claudeharness.ValidAgentBriefID)
//     is not a name WritePrivateBrief could ever have produced, so it is
//     left alone rather than guessed at;
//   - a symlink is never a legitimate brief file (WritePrivateBrief always
//     creates with O_EXCL|O_NOFOLLOW) and is removed regardless of whether
//     its name happens to match a referenced id — os.Remove unlinks the
//     symlink itself, never its target;
//   - anything else is kept if referenced, removed if orphaned.
func SweepOpeningPromptBriefs(homePath string) {
	records, err := agentstore.Load(agentstore.FilePath(homePath))
	if err != nil {
		return // no readable store: never guess which files are orphans
	}
	referenced := make(map[string]struct{}, len(records))
	for _, rec := range records {
		if rec.OpeningBriefID != "" {
			referenced[rec.OpeningBriefID] = struct{}{}
		}
	}
	dir := filepath.Join(homePath, "state", claudeharness.AgentBriefSpillDir)
	matches, err := filepath.Glob(filepath.Join(dir, "*.txt"))
	if err != nil {
		return
	}
	for _, path := range matches {
		id := strings.TrimSuffix(filepath.Base(path), ".txt")
		if !claudeharness.ValidAgentBriefID(id) {
			continue
		}
		info, err := os.Lstat(path)
		if err != nil {
			continue
		}
		if info.Mode()&os.ModeSymlink != 0 {
			_ = os.Remove(path)
			continue
		}
		if _, ok := referenced[id]; ok {
			continue
		}
		_ = os.Remove(path)
	}
}
